# Generated by Django 2.2.6 on 2020-02-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pastel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.FileField(blank=True, help_text='Digite seu nome', max_length=20, null=True, upload_to='')),
                ('endereço', models.TextField(blank=True, help_text='Digite seu endereço.', max_length=50, null=True)),
                ('quantidade', models.IntegerField()),
                ('data', models.DateTimeField(blank=True, help_text='Data do pedido.', null=True)),
                ('Tipo_Pastel', models.CharField(choices=[('IT', 'Italiano'), ('CA', 'Catupiri'), ('FG', 'Frango'), ('CA', 'Carne'), ('PI', 'Pizza')], default='CA', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Carne',
        ),
    ]
