# Generated by Django 2.2.6 on 2020-02-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0002_auto_20200228_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True, verbose_name='Digite seu nome')),
                ('endereço', models.TextField(blank=True, max_length=50, null=True, verbose_name='Digite seu endereço.')),
                ('quantidade', models.IntegerField()),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data do pedido.')),
                ('Tipo_Pizza', models.CharField(choices=[('CL', 'Calabreza'), ('CT', 'Catupiri'), ('FG', 'Frango'), ('CA', 'Carne'), ('BA', 'Banana'), ('MU', 'Muzzarella'), ('4Q', 'Quatro queijo')], default='CA', max_length=2, verbose_name='Escolha o tipo:')),
            ],
        ),
        migrations.AlterField(
            model_name='pastel',
            name='Tipo_Pastel',
            field=models.CharField(choices=[('IT', 'Italiano'), ('CT', 'Catupiri'), ('FG', 'Frango'), ('CA', 'Carne'), ('PI', 'Pizza')], default='CA', max_length=2, verbose_name='Escolha o tipo:'),
        ),
        migrations.AlterField(
            model_name='pastel',
            name='data',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do pedido.'),
        ),
        migrations.AlterField(
            model_name='pastel',
            name='endereço',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Digite seu endereço.'),
        ),
        migrations.AlterField(
            model_name='pastel',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Digite seu nome'),
        ),
    ]
