# Generated by Django 2.2.6 on 2020-02-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0003_auto_20200228_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True, verbose_name='Digite seu nome')),
                ('endereço', models.TextField(blank=True, max_length=50, null=True, verbose_name='Digite seu endereço.')),
                ('quantidade', models.IntegerField()),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data do pedido.')),
                ('Tipo_Suco', models.CharField(choices=[('LJ', 'Laranja'), ('LI', 'Limão'), ('MA', 'Manga'), ('MJ', 'Maracaju')], default='LJ', max_length=2, verbose_name='Escolha o tipo:')),
            ],
        ),
    ]
