# Generated by Django 2.2.6 on 2020-02-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0005_refrigerante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fritas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True, verbose_name='Digite seu nome')),
                ('endereço', models.TextField(blank=True, max_length=50, null=True, verbose_name='Digite seu endereço.')),
                ('quantidade', models.IntegerField()),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data do pedido.')),
                ('Tamanho', models.CharField(choices=[('ME', 'Média'), ('PE', 'Pequena'), ('GR', 'Grande')], default='PE', max_length=2, verbose_name='Escolha o tamanho:')),
            ],
        ),
        migrations.CreateModel(
            name='Saladas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=20, null=True, verbose_name='Digite seu nome')),
                ('endereço', models.TextField(blank=True, max_length=50, null=True, verbose_name='Digite seu endereço.')),
                ('quantidade', models.IntegerField()),
                ('data', models.DateTimeField(blank=True, null=True, verbose_name='Data do pedido.')),
                ('Tipo_salada', models.CharField(choices=[('AL', 'Alface'), ('RE', 'Repolho'), ('PE', 'Pepino')], default='AL', max_length=15, verbose_name='Escolha o tipo:')),
            ],
        ),
    ]
